service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - '!functions/**'
    - '!package.json'
    - '!package-lock.json'
    - '!.env'

functions:
  getProductsList:
    handler: functions/get-product-list-handler.getProductsList
    package:
      patterns:
        - functions/get-product-list-handler.js
    events:
      - httpApi:
          method: get
          path: /products
  getProductsById:
    handler: functions/get-product-by-id-handler.getProductsById
    package:
      patterns:
        - functions/get-product-by-id-handler.js
    events:
      - httpApi:
          method: get
          path: /products/{id}
  createProduct:
    handler: functions/create-product-handler.createProduct
    package:
      patterns:
        - functions/create-product-handler.js
    events:
      - httpApi:
          method: post
          path: /products
